# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_detail',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='function.UserProfile'),
        ),
    ]
