# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_auto_20180507_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='user',
        ),
    ]
