# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0004_remove_feature_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='company_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
